### PR TITLE
Proposal for uniform boolean comparison

### PR DESCRIPTION
**Pull request by lukas-zech-software**
Currently there are numerous variations of boolean comparison in our code.
This proposal aims to uniform this common code structure

This proposal describes 3 rules:

1) Compared constant value always second
2) Compare against false instead of negating operator
3) Also compare against true if multiple values in single condition

@gfke/frontend  Please add your thought about which of these 3 rules should be added to our conventions

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
I vote for 1) as it simply is the natural way you would read the code out loud

I also vote for 2) as the **!** operator is easy to overlook and also breaks natural reading of code

3) is more or less a consistent conclusion of 2) - I'm actually unsure about it without any personal preference

**Comment by Schnueggel** [comment]
1 => true 
2 => true 
3 => true

**Comment by Bruce17** [comment]
A note to 1):
Yoda style is always bad to read. We should put this rule into an extra topic e.g. "No Yoda conditions"

Your proposal: :+1:

**Comment by lukas-zech-software** [comment]
@Bruce17 
Depends on which yoda translator you use :wink: 
As I could not find a official translator, I'll stick to:
http://funtranslations.com/yoda

**Comment by Bruce17** [comment]
WTF there is a translater :-D

**Comment by lukas-zech-software** [comment]
Multiple in fact :smile: 

But most of them yield different results:
www.yodaspeak.co.uk/
http://discombobyoulated.blogspot.de/2013/09/convert-english-to-yoda-speak.html
https://www.apple.com/downloads/dashboard/justforfun/yodawidget.html

**Pull request merged**
