### PR TITLE
Usage of parentheses in boolean expression

### PR DESCRIPTION
**Pull request by lukas-zech-software**
Many developers, including my self, tend to wrap longer boolean expressions in parentheses *()* to improve readability of these statements.

But as we do not follow any convention on how or when to do this, the usage of parenthesis is highly inconsistent.

Therefore, this PR aims to uniform these usages.

There are 3 proposals in it:
1. Use them with all operators
2. Use them with boolean operators only
3. Never use them if not syntactically required

See the diff for details.

Please vote which proposal you prefer, or comment if you don't think this is necessary at all

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
@gfke/frontend Please share your thoughts on this

I prefer proposal number 2

**Comment by spanitz** [comment]
:+1: for proposal **2**

**Comment by Bruce17** [comment]
:+1: for proposal **3**

**Comment by lukas-zech-software** [comment]
@spanitz I mean operators like

AND (&&), OR (||), NOT (!)

I'd refer to them as boolean operators 

Is this synonym to logical operators? If not which expression would you prefer?

**Comment by Schnueggel** [comment]
for proposal 3

**Comment by spanitz** [comment]
@lukas-zech-software 

`AND/OR/NOT/XOR/...` are a subset of logical operators like `===`, `>=`, `<>` etc.. . Some call them boolean operators, but its less common (like me, I didn't know). That was confusing me.

> In logic, a logical connective (also called a logical operator) is a symbol or word used to connect two or more sentences (of either a formal or a natural language) in a grammatically valid way, such that the sense of the compound sentence produced depends only on the original sentences.
> - https://en.wikipedia.org/wiki/Logical_connective

It seems this term origins from the Boolean algebra (https://en.wikipedia.org/wiki/Boolean_algebra)

:smartass:

**Comment by mstein77** [comment]
I'm a 2 guy

**Comment by spanitz** [comment]
Proposal 2: **3** votes
Proposal 3: **2** votes

It gets hot in here... :sweat_smile:

**Comment by mstein77** [comment]
@nahody Finishing move, please :skull:

**Comment by spanitz** [comment]
Ok guys, any chance for progress here?

**Comment by spanitz** [comment]
Final result: Proposal 3

http://bit.ly/203GqSp

**Comment by lukas-zech-software** [comment]
Im merging this now with proposal 3

**Pull request merged**
