### PR TITLE
Code Style: avoid writing useless variables

### PR DESCRIPTION
**Pull request by Bruce17**
Sometimes variables are defined and used only once. This consumes cpu time, memory and is useless.

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
First I want to point out, that in my humble opinion, edge case performance is, by far, not as important as easily readable and maintainable code.
Declaring variables that are only consumed once do also not have a real performance impact in modern Javascript engines, as they will get optimised away.
See here for a small test case
http://jsperf.com/perfomance-impact-of-variable-declaration

The biggest difference towards not declaring I got in Chrome 44 on OS X was 0,8 %
On FireFox and Safari, the test with variables declared was even faster on almost all test runs (though I have no explanation for this)

That said, some variables **may** not make sense, when they do not contribute to the readability of the code e.g. if they save the result of a good named, declared function as in this example: 
```javascript
//good
return {
  productIds: getProductIds()
}

//also good when passing as argument 
noop(getProductIds());

//useless
var productIds = getProductIds();
return {
  productIds: productIds
}
//also useless
var productIds = getProductIds();
noop(productIds);

//then again, not so useless when ES6 is used properly on object declaration
const productIds = getProductIds();
return {
  productIds
}
```

What always makes sense and should definitely not be disallowed by any rule is saving the result of an anonymous/arrow function to a variable to describe it better, especially if provided as input for another function

```javascript
//What is going on here?
noop(array.map((x) => x*2 ));

//Ah now I can see!
var arrayWithValuesDoubled = array.map((x) => x*2 );
noop(arrayWithValuesDoubled);
```

Therefore I think, that the current proposal is way to strict an discourages understandable code.
I vote for rewording the proposal to something along the lines of
>>  Variables that are only used once, should only be declared if they improve readability or are deemed helpful in understanding the code

**Comment by Bruce17** [comment]
@lukas-zech-software 
:+1: to your rewording

If a comment is added to describe some variable that is only used once, I'm on your side. Without a description or any real ES6 usecase, it's still useless in my opinion.

**Comment by Schnueggel** [comment]
I also use an assignment to a variable if a following method call would get to long on the horizontal line.

**Comment by Bruce17** [comment]
If the method call would get to long, just wrap it.
We write code for humans to read, don't forget that.

```js
// bad
function foo() {
    const someVariable = 'test';
    return someRealeLongMethodName(and, aLotOf, verLongAttribute, names, andA, hugeNumber, ofAttributes, someVariable);
}

// good
function foo() {
    return someRealeLongMethodName(
        and, 
        aLotOf, 
        verLongAttribute,
        names, 
        andA, 
        hugeNumber, 
        ofAttributes,
        'test'
    );
}
```

**Comment by Schnueggel** [comment]
This only looks ok to me for simple params or object params

```js
const list = this.listFactory.getMergeList(this.view.kpiCollection, {sortNames: [DataSourceAlias.kpi.Units, DataSourceAlias.kpi.Price, DataSourceAlias.kpi.Value]});

this.view.table.kpi = new GraphTableData(['author.table.period', 'author.table.units', 'author.table.price', 'author.table.value'], list);

///Alternative could be
this.view.table.kpi = new GraphTableData(
      ['author.table.period', 'author.table.units', 'author.table.price', 'author.table.value'],
      this.listFactory.getMergeList(this.view.kpiCollection, {sortNames: [DataSourceAlias.kpi.Units, DataSourceAlias.kpi.Price, DataSourceAlias.kpi.Value]})
);
```
Both would be ok for me but I raised the maximum width of my code beyond A4 so the lines are still long

**Comment by Bruce17** [comment]
@Schnueggel 
Wrap it further and improve readability.

```js
this.view.table.kpi = new GraphTableData(
      ['author.table.period', 'author.table.units', 'author.table.price', 'author.table.value'],
      this.listFactory.getMergeList(
            this.view.kpiCollection, 
            {
                  sortNames: [
                        DataSourceAlias.kpi.Units,
                        DataSourceAlias.kpi.Price,
                        DataSourceAlias.kpi.Value
                  ]
            }
      )
);
```

**Comment by Schnueggel** [comment]
@Bruce17 
thats what I exactly dont want to do. Its getting less readable for me. I rather would pull out more vars.

**Comment by Bruce17** [comment]
@Schnueggel 
In you example, I've no problem with pulling out one or more variables. This is an acceptable case for me.

I was referring to code like this:

```js
function foo() {
    const ids = _.contains(ary, '123');
    return ids;
}
```

I saw that a lot in planet music.

**Comment by Schnueggel** [comment]
Ok I agree. Can the linter find such cases?

**Comment by Bruce17** [comment]
Well our jshint linter is not that mighty. A switch to ESlint may bring some improvements, because we are then able to write our own rules.

**Comment by lukas-zech-software** [comment]
There is a feature branch of yoso-gulp were I once started implementing ESLint, but that took more time than I initially thought and was dropped due to time pressure on other matters.

We might be able to resume that work, once we have a little more space to move

**Comment by Bruce17** [comment]
@lukas-zech-software :+1:

**Comment by Bruce17** [comment]
I updated the wording and examples.

**Comment by Bruce17** [comment]
Some other opinions?

**Comment by lukas-zech-software** [comment]
I fully agree with the current wording :+1: 

@gfke/frontend Any other suggestions or objections?

If not I would vote to merge this soon

**Comment by spanitz** [comment]
I would like to add something in this context: The declaration of variables without an assignment does nothing for readability (means: blows up code) or doesn't affect runtime in any way.

Unfortunately I could see this quite often throughout our codebase. e.g.

``` javascript
// bad
var foo,
     bar,
     baz;

foo = 5; // bar and baz were assigned 50 lines below...

// neat
var foo = 5,
     bar = {},
     baz = false;
```
Some code rules of other languages, this is explicitly referred to as clean.

**Comment by Bruce17** [comment]
@spanitz I added your proposal.

**Comment by Bruce17** [comment]
I'll merge this PR in this afternoon, so feel free to comment until then.

**Pull request merged**
