### PR TITLE
Code Style: suggestion on how to deal with less/useless new lines

### PR DESCRIPTION
**Pull request by Bruce17**
Some code seems to be unstructured and lacks new lines. New lines helps you and especially other developers to understand your code. There are also places with useless new lines where none is needed.

This is a proposel on how to deal with too less/too much new lines.

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
:+1: I like it

I miss a definit rule(s) describing when or when not to insert a new line but the examples show pretty good what to structure with new line and what not

**Comment by Bruce17** [comment]
Some other opinions?

**Comment by Drexonom** [comment]
Define rules where to put a new line and where to omit it.

Keep the examples as short as possible - eg. theres no need to provide a whole class to show that a new line at the beginning of a function is bad.

**Comment by Bruce17** [comment]
@Drexonom the example also shows some newline behavior in the class itself and on the outside. I tried to cover as much cases as possible with one example.

**Comment by Drexonom** [comment]
You're right... Then I would suggest to break the "big" example into smaller pieces - this might help you to define generic rules which further increases the understanding of the reader.

**Comment by Bruce17** [comment]
Updated example code.

**Comment by Drexonom** [comment]
:+1:

**Comment by lukas-zech-software** [comment]
Nice wording an examples!

Fully agree :+1: 

@gfke/frontend Any other suggestions or objections?

If not I would vote to merge this soon

**Pull request merged**
