### PR TITLE
More strict boolean comparison

### PR DESCRIPTION
**Pull request by lukas-zech-software**
We had a discussion about the boolean comparison convention added last weak, as it left the comparison of single statements against true as an optional choice.
https://github.com/gfke/book-insights/pull/15#discussion_r36067642

This new proposal requires all  boolean comparison to be against on of the two static boolean values.

This improves the readability as all boolean comparisons are now written exactly same and also prevents accidental implicit comparison if the checked variable holds another type than *Boolean*

@gfke/frontend Please comment if you want to accept this more verbose way or if you'd rather keep the current convention which keeps this optional

### CODE REVIEW

**Comment by spanitz** [comment]
Imagine the following highly engineered lines of code:

```
if (1)     // truthy
if (0)     // falsy
if (' ')   // truthy
if (!-1)   // falsy

if (1 === true)   // evaluates to false
if (0 === true)   // evaluates to false
if (' ' === true) // evaluates to false
if (-1 === false) // evaluates to false

**Comment by mstein77** [comment]
In PHP all of the above examples would evaluate to true

**Comment by spanitz** [comment]
Got another one:

``` javascript

isFoo() {
    return '1';
}

if (isFoo()) // truthy
if (isFoo() == 1) // yeah, absolutely true

if (isFoo() === true) // evaluates to false
if (isFoo() === 1) // evaluates to false
// or: refactor isFoo()!
```

**Comment by mstein77** [comment]
Methods having the is- or has- prefix MUST always return a boolean. So I would say the last examples should not happen.

**Comment by spanitz** [comment]
Not in our code, right. :)

**Comment by spanitz** [comment]
@lukas-zech-software +1

**Comment by mstein77** [comment]
I see the point of type checking but the verbose way makes it IMHO less readable:

if (_.isArray($foo) && _.isEmpty($foo)) {
if (!_.isUndefined($foo))

VS

if (_.isArray($foo) === true && _.isEmpty($foo) === true) {
if (_.isUndefined($foo) === false)) 

The last double negation really makes you check it twice ;-)
Just my 2 cents.

**Comment by lukas-zech-software** [comment]
Another solution would be to have negated syntactic sugar functions for all comparison functions
```
if( _.isFoo(foo) ) {...}
if( _.isNotFoo(foo) ) {...}
```

I did that in the SessionViewStateModel, if you want to see a real world example:
https://github.com/gfke/dashboard-sessionViewStateModel/blob/master/source/index.es6.js#L63

But of course this leads to problems on external libraries like lodash, as they do not always provide these negated methods

```
if( _.isArray(foo) ) {...}
if( _.isNotArray(foo) ) {...} // sadly not there
```

Of course we could fork it and and them ourselves ...

**Comment by lukas-zech-software** [comment]
@gfke/frontend 
more opinions anyone?

**Comment by spanitz** [comment]
Just keep it open, as long as the team is not fully committed.

**Comment by Bruce17** [comment]
Good:
```js
if (foo === true) // true check
if (bar === false) // explicit false check
if (isFoo()) // true check
if (isFoo() === false) // explicit false check
if (hasBar()) // true check
if (hasBar() === false) // explicit false check
```

Well, unnecessary:
```js
if (isFoo() === true)
if (hasBar() === true)
```

Methods starting with `is<Name>` or `has<Name>` should **always** return a boolean.
Write tests to check that behavior if necessary.

**Comment by spanitz** [comment]
I totally agree with the proposal from @Bruce17. Please add `can<Name>` has possible verb. :+1:

**Comment by lukas-zech-software** [comment]
I created the an opposite proposal to this in another PR
https://github.com/gfke/coding-styles/pull/8

If you all agree with that one, we can decline this and accept the other one

**Comment by Schnueggel** [comment]
If available I would prefer verbose version ```isNotInFoo(key)``` where ever possible this shortens the code in the view.

I think === true is perhaps unnecessary but could be more consistent if we already use === false. Code rythm is important for my feelings :dancer:  :D

**Comment by spanitz** [comment]
Consistency was also an argument of mine (See https://github.com/gfke/book-insights/pull/15#discussion_r36067642). But as a developer you just need to remember a single exception: The unnecessarity of `<is|has|can>Foo === true`

**Comment by lukas-zech-software** [comment]
@Schnueggel 
That was also my intention, keeping the look/rhythm of the code as uniform as possible

My preferred  solution would still be having a negated method  for everything 
```
has(){...}
hasNot(){ return has() === false; }

//yes we
can(){}

//no we
canNot(){ return can() === false; }
```

**Comment by mstein77** [comment]
What about having a not() function...this could used as wrapper for third party check-methods:

if (not(_.isEmpty(foo))

**Comment by Bruce17** [comment]
My suggestion:  keep it simple!

Readability and code convention are one thing, but also keep your code performance in mind. Tons of calls to "checker" methods will reduce the applications performance.

**Comment by spanitz** [comment]
Ok, just to summarize:

* Negated boolean comparsion always identically against false ` hasFoo() === false` instead of `!hasFoo()` or `hasFoo == false`

* The other case, comparing against true simply leave the comparator `hasFoo()` instead of 'hasFoo() === true' 

* Negated methods were not part of this proposal and aren't relevant for a the convention itself. As they are, as @lukas-zech-software mentioned, syntactical sugar.

**Comment by lukas-zech-software** [comment]
The consent seems to reject this pull request and accept the less stricht version [https://github.com/gfke/coding-styles/pull/8]

**Comment by lukas-zech-software** [comment]
Rejected in favour of less strict convention

**Pull request closed without merging**
