### PR TITLE
Less strict boolean comparison

### PR DESCRIPTION
**Pull request by lukas-zech-software**
This PR is basically the negation of https://github.com/gfke/coding-styles/pull/6

### CODE REVIEW

**Comment by Bruce17** [comment]
:+1:

**Comment by mstein77** [comment]
:+1: :+1:

**Comment by spanitz** [comment]
:+1:

**Comment by lukas-zech-software** [comment]
This convention was accepted by most developer and was favoured over the strict version which was rejected [https://github.com/gfke/coding-styles/pull/6]

**Pull request merged**
